vcard/blog/urls.py
from django.urls import path
from .views import *

app_name ='blog'

urlpatterns=[
    path('',blog_list,name='blog_list'),
    path('<slug:cslug>/',blog_list,name='blog_list_by_cslug'),
    path('',blog_list_by_tag,name='blog_list_by_tag'),
    path('detail/<slug:slug>/',blog_detail,name='blog_detail'),
]

vcard/vcard/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import home
from guestbook.views import *

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('blog/',include('blog.urls')),
    path('post_message/',post_message,name='post_message'),
    path('',home,name='home'),
    path('admin/', admin.site.urls),
    path('tinymce/',include('tinymce.urls')),
    path('account/',include('account.urls')),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

vcard/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.shortcuts import reverse
# from tinymce.models import HTMLField
from taggit.managers import TaggableManager

# Create your models here.

class Category(models.Model):
    name=models.CharField('分类名',max_length=50)
    slug=models.SlugField('url缩写',max_length=100)
    description=models.TextField('备注说明',max_length=300,null=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    STATUS_CHOICES=(
        ('draft','草稿'),
        ('published','发布'),
    )
    title=models.CharField('文章标题',max_length=200)
    slug=models.SlugField('url缩写',max_length=100,unique_for_date='publish')

    category=models.ForeignKey(Category,related_name='blog_posts',null=True,on_delete=models.SET_NULL)
    author=models.ForeignKey(User,related_name='blog_posts',null=True,on_delete=models.SET_NULL)

    body=models.TextField('正文')
    # body=HTMLField('正文')
    image=models.ImageField('图片',null=True,blank=True,upload_to='uploads/')

    publish=models.DateTimeField('发布时间',default=timezone.now)
    created=models.DateTimeField('创建时间',auto_now_add=True)
    updated=models.DateTimeField('更新时间',auto_now=True)
    status=models.CharField('文章状态',choices=STATUS_CHOICES,default='draft',max_length=100)

    tags=TaggableManager()


    def __str__(self):
        return self.title


    class Meta:
        ordering=['-publish']

    # def get_absolute_url(self):
    #     return reverse('blog:blog_detail',args=[
    #             self.publish.year,
    #             self.publish.month,
    #             self.publish.day,
    #             self.slug
    #     ])


class Comment(models.Model):
    post=models.ForeignKey(Post,related_name='comments',null=True,on_delete=models.SET_NULL)
    name=models.CharField('姓名',max_length=100)
    email=models.EmailField('邮箱',max_length=100)
    message=models.TextField('消息')
    active=models.BooleanField('是否有效',default=True)
    created=models.DateTimeField('提交时间',auto_now_add=True)

    class Meta:
        ordering=['-created']

    def __str__(self):
        return f'{self.name}对{self.post}有评论' 

vcard/blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Category,Post,Comment
from django.db.models import Count
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from taggit.models import Tag


# Create your views here.

def blog_list(request,cslug=None):
    """博客列表页"""
    object_list=Post.objects.filter(status='published')
    if cslug:
        category=get_object_or_404(Category,slug=cslug)
        object_list=object_list.filter(category=category)
    paginator=Paginator(object_list,5)
    page=request.GET.get('page')
    try:    
        posts=paginator.page(page)
    except PageNotAnInteger:
        posts=paginator.page(1)
    except EmptyPage:
        posts=paginator.page(paginator.num_pages)
    return render(request,'blog/blog-list.html',{'page':page,'posts':posts,'paginator':paginator})


def blog_list_by_tag(request,ytag=None):
    object_list=Post.objects.filter(status='published')
    if ytag:
        tag=get_object_or_404(Tag,tag=ytag)
        object_list=object_list.filter(tags=tag)
    paginator=Paginator(object_list,5)
    page=request.GET.get('page')
    try:    
        posts=paginator.page(page)
    except PageNotAnInteger:
        posts=paginator.page(1)
    except EmptyPage:
        posts=paginator.page(paginator.num_pages)
    return render(request,'blog/blog-list.html',{'page':page,'posts':posts,'paginator':paginator})


def blog_detail(request,slug):
    post=get_object_or_404(Post,slug=slug)
    """相关日志"""
    post_tags_ids = post.tags.values_list('id',flat=True)
    similar_posts = Post.objects.filter(tags__in= post_tags_ids).exclude(id = post.id)
    similar_posts = similar_posts.annotate(same_tags = Count('tags')).order_by('-same_tags','-publish')[:4]
    return render(request,'blog/blog-detail.html',{'post':post,'similar_posts':similar_posts})

vcard/templates/blog/blog-detail.html
{% extends "base.html" %}

{% load blog_tags %}

{% block title %}
    {{post.title}}
{% endblock title %}

{% block content %}
<section id="profile" class="item">
    <h2 class="item-title"><a href="/"><span class="title">个人资料</span><span class="icon-user"></span></a></h2>
    <div class="item-border"><span></span></div>
</section><!-- /#profile -->

<section id="post" class="item">
    <h2 class="item-title"><a href="#"><span class="title">日子正文</span> <span class="icon-blog"></span></a></h2>

        <div class="item-cont clearfix">
            <div class="col535 fl-left">
                <h2 class="post-title">{{ post.title }}</h2>
                <div class="post-info">
                    {{post.publish|date:'m月d日'}} <a href="#"></a>  <a href="#" title="Posts by admin" rel="author">{{post.author.username }}</a> 发布于
                    <a href="#">{{post.category.name }}</a>
                    <a href="#" class="comments-link">{{post.comments.count }} 个评论</a>
                </div>

                <div class="post-cont wp-cont">
                    {% if post.image %}
                       <div class="entry-photo"><img src="/media/{{ post.image }}" alt="{{post.image }}" /></div>
                    {% endif %} 
                    {{post.body|safe }}
                </div>

                <div class="post-bottom clearfix">
                    <div class="post-tags"><span>关键字标签:</span> 
                        {% for tag in post.tags.all %}
                            <a href="#">{{tag }}</a>
                        {% endfor %}
                         
                    </div>
                    <div class="post-share">
                        <span>Share:</span>
                        <a target="_blank" href="http://twitter.com/" class="share-tw" title="Twitter">&nbsp;</a>
                        <a target="_blank" href="http://www.facebook.com/" class="share-fb" title="Facebook">&nbsp;</a>
                        <a target="_blank" href="http://pinterest.com/" class="share-p" title="Pinterest">&nbsp;</a>
                        <a target="_blank" class="share-in" href="http://www.linkedin.com/" title="Linkedin">&nbsp;</a>
                    </div>
                </div>

                <div class="post-comments">
                    <div id="respond" class="section block_leave_comments form no_comments">
                        <h3>Leave a Comment</h3>
                        <a id="cancel-comment-reply-link" href="#" style="display:none;">cancel reply</a>
                        <form action="http://vcard-html.royalmasters.net/post" method="post">
                            <div class="form-col form-marg small fl-left">
                                <label>Name<span>*</span></label>
                                <input name="author" id="author" size="22" tabindex="1" aria-required="true" class="input-name form-item" type="text">
                            </div>
                            <div class="form-col small fl-left">
                                <label>Email<span>*</span></label>
                                <input name="email" id="email" size="22" tabindex="2" aria-required="true" class="input-email form-item" type="text">
                            </div>
                            <div class="form-col">
                                <label>Message<span>*</span></label>
                                <textarea name="comment" id="comment" cols="39" rows="4" tabindex="4" aria-required="true" class="textarea-comment form-item"></textarea>
                            </div>
                            <div id="comment-submit" class="form-btn">
                                <div class="button">
                                    <input name="submit" id="submit" tabindex="5" value="Leave a Comment" class="comment-submit general_button default btn" type="submit">
                                </div>
                                <input name="comment_post_ID" value="68" id="comment_post_ID" type="hidden">
                                <input name="comment_parent" id="comment_parent" value="0" type="hidden">
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="col230 fl-right">
                <aside id="sidebar">
                    <div class="widget">
                        <h2>日志分类 {% total_posts %}</h2>
                        {% get_all_categories as categories %}
                        <ul>
                            {% for c in categories %}
                            
                                <li><a href="{% url 'blog:blog_list_by_cslug' c.slug  %}" title="View all posts filed under Audio">{{c.name }}</a></li>
                            {% endfor %}
                            
                        </ul>
                    </div>

                    {% show_latest_posts 4 %}

                    <div class="widget">
                            <h2>相关日志</h2>
                            <ul>
                                {% for item in similar_posts %}
                                    <li><a href="{% url 'blog:blog_detail' item.slug %}">{{ item.title }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>

                    <div class="widget">
                        <h2>标签云集</h2>
                        {% get_all_tags as tags %}
                        <div class="tagcloud">
                            {% for tag in tags  %}
                                 <a href="#" title="audio">{{tag }}</a>
                            {% endfor %}
                           
                        </div>
                    </div>

                    <div class="widget">
                        <h2>Archives</h2>
                        <ul>
                            <li><a href="#">December 2013</a></li>
                            <li><a href="#">November 2013</a></li>
                        </ul>
                    </div>

                    <div class="widget">
                        <h2>Meta</h2>
                        <ul>
                            <li><a href="#">Log in</a></li>
                            <li><a href="#" title="Syndicate this site using RSS 2.0">Entries <abbr title="Really Simple Syndication">RSS</abbr></a></li>
                            <li><a href="#" title="The latest comments to all posts in RSS">Comments <abbr title="Really Simple Syndication">RSS</abbr></a></li>
                            <li><a href="#" title="Powered by WordPress, state-of-the-art semantic personal publishing platform.">WordPress.org</a></li>
                        </ul>
                    </div>
                </aside>

            </div>
        </div>
    <div class="item-border"><span></span></div>
</section><!-- /#post -->
{% endblock content %}

vcard/templates/blog/blog-list.html
{% extends "base.html" %}

{% load blog_tags %}

{% block title %}
blog首页
{% endblock title %}

{% block content %}
<section id="profile" class="item">
        <h2 class="item-title"><a href="/"><span class="title">个人资料</span><span class="icon-user"></span></a></h2>
        <div class="item-border"><span></span></div>
    </section><!-- /#profile -->

    <section id="blog" class="item">
        <h2 class="item-title"><a href="http://vcard.royalmasters.net/blog"><span class="title">日志列表</span> <span class="icon-blog"></span></a></h2>

        <div class="item-cont clearfix">

            <div class="col535 fl-left">

                {% for post  in posts %}
                
                <article class="entry-box">
                    <header class="entry-header">
                        <h2 class="post-title"><a href="{% url 'blog:blog_detail' post.slug %}">{{ post.title }}</a></h2>
                        <div class="post-info">
                            由作者 <a href="#" title="Posts by admin" rel="author">{{post.author }}</a> 发布于
                            <a href="#" title="View all posts in Creative" rel="category tag">{{post.category.name }}</a>
                        </div>
                    </header>
                    <div class="entry-content">
                        {% if post.image %}
                            <div class="entry-photo"><img src="/media/{{ post.image }}" alt="{{post.title}}" /></div>
                        {% endif %}

                        <div class="clearfix">
                            <div class="entry-data">
                                <span class="month">{{ post.publish|date:'m'}}</span>
                                <span class="day">{{ post.publish|date:'d' }}</span>
                                <a href="#" class="comments-link"><i class="comments-icon"></i>{{ post.comments.count }}</a>
                            </div>
                            <div class="entry-text">
                                <div><p>{{ post.body|truncatewords:40|safe }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <footer><a class="entry-more btn" href="{% url 'blog:blog_detail' post.slug %}">阅读全文</a></footer>
                </article>
                {% endfor %}
                <div id="pageination" class="clearfix">
                    <ul class="page-numbers">
                        {% if posts.has_previous %}
                            <li><a class="page-numbers" href="?page={{posts.previous_page_number }}">上一页</a></li>                        
                        {% endif %}
                        {% for i in paginator.page_range %}
                            {% if i == posts.number %}
                                <li><span class="page-numbers current">{{i}}</span></li>
                            {% else %}
                                <li><a class="page-numbers" href="?page={{i}}">{{i}}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if posts.has_next  %}
                            <li><a class="page-numbers" href="?page={{posts.next_page_number }}">下一页</a></li>                                                                   
                        {% endif %}
                    </ul>
                </div>
            </div>

            <div class="col230 fl-right">
                <aside id="sidebar">
                    <div class="widget">
                        <h2>所有分类{% total_posts %}</h2>
                        {% get_all_categories as categories %}
                        <ul>
                            {% for c in categories  %}
                                <li><a href="{% url 'blog:blog_list_by_cslug' c.slug  %}" title="View all posts filed under Audio">{{c.name }}</a></li>
                            {% endfor %}
                            
                        </ul>
                    </div>

                    {% show_latest_posts 3 %}

                    <div class="widget">
                        <h2>标签云集</h2>
                        {% get_all_tags as tags %}
                        <div class="tagcloud">
                            {% for tag in tags %}
                                <a href="{% url 'blog:blog_list_by_tag' %}?tag={{ tag }}" title="audio">{{tag }}</a>
                            {% endfor %}
                            
                        </div>
                    </div>

                    <div class="widget">
                        <h2>Archives</h2>
                        <ul>
                            <li><a href="#">December 2013</a></li>
                            <li><a href="#">November 2013</a></li>
                        </ul>
                    </div>

                    <div class="widget">
                        <h2>Meta</h2>
                        <ul>
                            <li><a href="#">Log in</a></li>
                            <li><a href="#" title="Syndicate this site using RSS 2.0">Entries <abbr title="Really Simple Syndication">RSS</abbr></a></li>
                            <li><a href="#" title="The latest comments to all posts in RSS">Comments <abbr title="Really Simple Syndication">RSS</abbr></a></li>
                            <li><a href="#" title="Powered by WordPress, state-of-the-art semantic personal publishing platform.">WordPress.org</a></li>
                        </ul>
                    </div>
                </aside>
            </div>
        </div><!-- /.item-cont -->

        <div class="item-border"><span></span></div>
    </section><!-- /#blog -->

{% endblock content %}

vcard/templates/blog/latest_posts.html
<div class="widget">
    <h2>最新日志</h2>
    <ul>
        {% for item in latest_posts %}
            <li><a href="{% url 'blog:blog_detail' item.slug %}">{{ item.title }}</a></li>
        {% endfor %}
    </ul>
</div>